MyBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from blog.views import user_login, user_logout
from django.conf.urls import url, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit_profile/', views.edit_profile, name = 'edit_profile'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('like/', views.like_post, name='like_post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .views import *
urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', post_detail, name = "post_detail"),
    url(r'post_create/$', post_create, name='post_create'),
    url(r'^(?P<pk>\d+)/post_edit/$', post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/post_delete/$', post_delete, name='post_delete'),
    url(r'^(?P<pk>\d+)/favourite_post/$', favourite_post, name='favourite'),
    url(r'favourites/', post_favourite_list, name='post_favourite_list'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings

# Create your models here.

class Post(models.Model):
    #object = models.Manager()      #our default Manager
    #published = PublishedManage()  #our Custom Model Manager
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('publised','Published'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    restrict_comment = models.BooleanField(default=False)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    #class Meta:
    #        ordering = ['-id']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("post_detail", args=[self.pk])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)

    def __str__(self):
        return "Profile of user ()".format(self.user.username)

class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.post.title + "Image"

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, related_name="replies", on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

blog/forms.py
from django  import forms
from .models import *
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
            'restrict_comment',
        )

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
            'restrict_comment',
        )

class UserLoginForm(forms.Form):
    username = forms.CharField(label="")
    password = forms.CharField(label="", widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs= {'placeholder':'Enter password here...'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs= {'placeholder': 'Confirm password here...'}))
    class Meta:
        model = User
        fields= (
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'dob',
            'photo',
        )

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!!', 'rows': '4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = (
            'content',
        )

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from .forms import *
from .models import *
from django.forms import modelformset_factory
from django.contrib import messages
from django.template.loader import render_to_string

def post_list(request):
    posts_list = Post.objects.all().order_by('-id')
    query = request.GET.get('q')
    if query:
        posts_list = Post.objects.filter(
            Q(title__icontains=query)|
            Q(author__username=query)|
            Q(body__icontains=query)
        )
    paginator = Paginator(posts_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 3
    else:
        (start_index, end_index) = proper_pagination(posts, index = 4)
    page_range = list(paginator.page_range)[start_index: end_index]

    context = {
        'posts':posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)

def proper_pagination(posts, index):
    start_index = 0
    end_index = 3
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favourite = False
    if post.likes.filter(id = request.user.id).exists():
        is_liked = True
    if post.favourite.filter(id = request.user.id).exists():
        is_favourite = True
    if request.method == "POST":
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id = reply_id)

            comment = Comment.objects.create(post=post, user = request.user, content=content, reply = comment_qs)
            comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    context = {
        'post':post,
        'is_liked': is_liked,
        'is_favourite': is_favourite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/post_detail.html', context)

def favourite_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if post.favourite.filter(id = request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())

def post_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
        'favourite_posts': favourite_posts,
    }
    return render(request, 'blog/post_favourite_list.html', context)


def like_post(request):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    is_liked = False

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect(post.get_absolute_url())


def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            for f in formset:
                try:
                    photo = Images(post=post, image=f.cleaned_data['image'])
                    photo.save()
                    #   return redirect('post_list')
                except Exception as e:
                    break
            messages.success(request, "Post has been successfully created.")
            return redirect('post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset = Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)

def post_edit(request, pk):
    post = get_object_or_404(Post, id=pk)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)

    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)
            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id = request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        d = Images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()
            messages.success(request, "{} has been successfull updated!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset = Images.objects.filter(post=post))
    context = {
        'form': form,
        'post': post,
        'formset': formset,
    }
    return render(request, 'blog/post_edit.html', context)

def post_delete(request, pk):
    post = get_object_or_404(Post, id = pk)
    if request.user !=post.author:
        raise Http404()
    post.delete()
    messages.warning(request, 'post has been successfully deleted!')
    return redirect('post_list')

def user_login(request):
    if request.method == "POST":
        form =  UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username = username, password = password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not active")
            else:
                return HttpResponse("User is None")

    else:
        form = UserLoginForm()
    context = {
        'form': form,
    }
    return render(request, 'blog/login.html', context)

def user_logout(request):
    logout(request)
    return redirect('post_list')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user = new_user)
            return redirect('post_list')
    else:
        form =  UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'blog/edit_profile.html', context)

templates/blog/alerts.html
<div class="messages">
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">
                {{ message }}
            </p>
        {% endfor %}
    {% endif %}
</div>

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %}Neko{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    {% include 'blog/navbar.html' %}
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
        {% include 'blog/footer.html' %}
    </div>

<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(event){
        $('.delete').click(function(){
            return confirm("Are you sure to delete this post?");
        });

        $('.reply-btn').click(function(){
            $(this).parent().parent().next('.replied-comments').fadeToggle()
        });
    });
</script>-->
</body>
</html>

<!---$(document).on('click','#like'), function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
                type: 'POST',
                url: '{% url "like_post" %}',
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                    $('#like-section').html(response['form'])
                    console.log($('#like-section').html(response['form']));
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });*/
-->

templates/blog/comments.html
<div class="container-fluid mt-2">
        <div class="form-group row">
            <form method="post" class="comment-form" action=".">
                {% csrf_token %}
                {{ comment_form.as_p }}
                {% if request.user.is_authenticated %}
                    <input type="submit" value="Submit" class="btn btn-outline-success">
                {% else %}
                    <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                {% endif %}
            </form>
        </div>
    </div>

    {{ comments.count }}Comment{{ comments|pluralize }}
    {% for comment in comments %}
        <blockquote class="blockquote">
            <p class="mb-0"><small>{{ comment.content }}</small></p>
            <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
                <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
            </footer>
        </blockquote>
    <div class="replied-comments container md-2">
        {% for reply in comment.replies.all %}
            <blockquote class="blockquote">
                <p class="mb-0"><small>{{ reply.content }}</small></p>
                <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small></footer>
        </blockquote>
        {% endfor %}
        <div class="form-group row">
            <form method="post" class="reply-form" action=".">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                {{ comment_form.as_p }}
                {% if request.user.is_authenticated %}
                    <input type="submit" value="Submit" class="btn btn-outline-success">
                {% else %}
                    <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                {% endif %}
            </form>
        </div>
    </div>
    {% endfor %}

templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block title %}Edit Profile | {{ block.super }}{% endblock %}
{% block content %}
    <form action="{% url 'post_list' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <input type="submit" value="Save changes" class="btn btn-outline-success">
    </form>
{% endblock %}

templates/blog/footer.html
<footer class="footer text-white">
    <div class="row">
        <div class="col-md-4">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
        </div>
        <div class="col-md-4">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
        </div>
        <div class="col-md-4">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
        </div>
    </div>
</footer>

templates/blog/like_section.html
{{ total_likes }} Like {{ total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'like_post' %}" method="post">
    {% csrf_token %}
    {% if is_liked %}
        <button type="submit" id="dislike" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
    {% else %}
        <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
    {% endif %}
</form>
{% endif %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <small>
            <a href="{% url 'register' %}">Register</a>|
        </small>
    <br>
    <input type="submit" value="Login" class="btn btn-outline-success">
    <p>--OR--</p>
    <a href="{% url 'social:begin' 'github' %}">
       <button type="button" name="button" class="btn btn-primary">Github</button>
    </a>
    <a href="{% url 'social:begin' 'google-oauth2' %}">
       <button type="button" name="button" class="btn btn-danger">Google+</button>
    </a>
    </form>
{% endblock %}

templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'post_list' %}">Neko</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <form class="form-inline my-2 my-lg-0" action="{% url 'post_list' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
    <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdoen">
            <a class="dropdown-item" href="{% url 'post_create' %}">Post create</a>
            <a class="dropdown-item" href="{% url 'post_favourite_list' %}">Favourite</a>
        </li>
        <li class="nav-item dropdown">
            <a class="dropdown-item" href="{% url 'edit_profile' %}"><img src="{{ request.user.profile.photo.url }}" alt="" class="navbar-img"></a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">Login</a>
            </li>
        {% endif %}
    </ul>

  </div>
</nav>

templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% block title %}Post create{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.as_table }}
        <input type="submit" value="Create" class="btn btn-outline-success">

    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}
{% block content %}
{% include 'blog/alerts.html' %}

<div class="container-fluid">
    <h3>{{ post.title }}</h3>
    <small>Post created by : {{post.author}}</small>
    <p>{{post.body}}</p>
</div>
<div class="row gallery">
    {% for p in post.images_set.all %}
        <div class="col-md-3">
            <img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
        </div>
    {% endfor %}
</div>
<div id="like-section">
    {% include 'blog/like_section.html' %}
</div>

{% if post.author == request.user %}
<div class="section-1" style="float:right;">
    <a href="{% url 'post_edit' post.id %}">
        <button type="button" class="btn btn-outline-success">Edit</button>
    </a>
    <a href="{% url 'post_delete' post.id %}" id="delete">
        <button type="button" class="btn btn-danger">Delete</button>
    </a>
</div>
{% endif %}

<br>

{% if not post.restrict_comment %}
    <div class="main-comment-section">
        {% include 'blog/comments.html' %}
    </div>
{% endif %}
{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.id }}|Edit {% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for f in formset %}
            {{ f.as_p }}
        {% endfor %}
        <input type="submit" value="Update" class="btn btn-success">
    </form>
{% endblock %}

templates/blog/post_favourite_list.html
{% extends 'blog/base.html' %}
{% block title %}Favourite{% endblock %}
{% block content %}
<div class="row">
    {% for p in favourite_posts %}
    <div class="col-md-6">
        <div class="img-thumbnail">
            <a href="{% url 'post_detail' p.id %}" >{{p.title}}</a><small style="float:right">{{p.created}}</small><br/>
            Author : {{p.author}}<br>
            {{p.body}}
        <br/>

        </div>
    </div>
    {% empty %}
    <div class="container-fluid">
        <h3>No Posts Found having search query "{{ request.GET.q }}"</h3>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}Welcom to {{block.super}}{% endblock %}
{% block content %}
{% include 'blog/alerts.html' %}

<div class="row">
    {% for p in posts %}
    <div class="col-md-6">
        <div class="img-thumbnail">
            <a href="{% url 'post_detail' p.id %}" >{{p.title}}</a><small style="float:right">{{p.created}}</small><br/>
            Author : {{p.author}}<br>
            {{p.body}}
        <br/>

        </div>
    </div>
    {% empty %}
    <div class="container-fluid">
        <h3>No Posts Found having search query "{{ request.GET.q }}"</h3>
    </div>
    {% endfor %}
</div>
<ul class="pagination">
    {% if posts.has_previous %}
        <li class="page-item">
            <a href="?page={{ posts.previous_page_number }}" class="page-link">Previous</a>
        </li>
    {% endif %}
    {% for p in page_range %}
        {% if posts.number == p %}
            <li class="page-item active">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
        <li class="page-item">
            <a href="?page={{ posts.next_page_number }}" class="page-link">Next</a>
        </li>
    {% endif %}
</ul>
{% endblock %}

templates/blog/registration.html
{% extends 'blog/base.html' %}